#ifndef _SYSTEM_CONF_H_
#define _SYSTEM_CONF_H_

#define TARGET_ECU_STM32F0DISCOVERY 0
#define TARGET_ECU_STM32F4DISCOVERY 1
#define TARGET_ECU_STM32F103C8_ARDUINO 2

#define TARGET_ECU TARGET_ECU_STM32F103C8_ARDUINO

#endif
