#ifndef _SYSTEM_CONF_H_
#define _SYSTEM_CONF_H_

#define CLK_SOURCE_HSI      0
#define CLK_SOURCE_HSE_OSC  1
#define CLK_SOURCE_HSE_EXT  2

#define CLK_SOURCE CLK_SOURCE_HSE_EXT

#define F_SYSTEM 48000 /* kHz */

#define TARGET_ECU_STM32F0DISCOVERY 0
#define TARGET_ECU_STM32F4DISCOVERY 1

#define TARGET_ECU TARGET_ECU_STM32F4DISCOVERY

#endif
